# Generated by Django 4.0.4 on 2022-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PROD_VALOR',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
