# Generated by Django 4.0.4 on 2022-07-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_producto_prod_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_proveedor',
            name='FAC_VIGENCIA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fact_proveedor',
            name='USU_USERNAME',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='backend.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='BOL_IVA',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='BOL_SUBTOTAL',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='det_fact_proveedor',
            name='DFT_VALOR',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalle_boleta',
            name='DET_VALOR',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fact_proveedor',
            name='FAC_TOTAL',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='USU_USERNAME',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
